version: "3.7"
services:
  backend:
    container_name: myjs-backend-test
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile.dev
    volumes:
      - ./packages/backend:/opt/app/packages/backend:cached
      - volume-myjs-node_modules:/opt/app/node_modules:delegated
      - volume-myjs-backend-node_modules:/opt/app/packages/backend/node_modules:delegated
    ports:
      - "4001:4001"
    env_file:
      - ./packages/backend/.env.test
    environment:
      - NODE_ENV=test
      - PORT=4001
      - DB_URL=postgresql://admin:password@myjs-database-test:5432/myjs
    depends_on:
      - database
    entrypoint: /opt/app/packages/backend/entrypoint.dev.sh

  database:
    container_name: myjs-database-test
    image: postgres:13-alpine
    ports:
      - "50001:5432"
    environment:
      - POSTGRES_INITDB_ARGS="--no-locale"
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myjs

volumes:
  volume-myjs-node_modules:
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
  volume-myjs-backend-node_modules:
    driver_opts:
      type: none
      device: ${PWD}/packages/backend/node_modules
      o: bind

networks:
  default:
    name: myjs-test
