version: "3.7"
services:
  backend:
    container_name: myjs-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./packages/backend:/app/packages/backend:cached
      - volume-myjs-node_modules:/app/node_modules:cached
      - volume-myjs-backend-node_modules:/app/packages/backend/node_modules:cached
    ports:
      - "4000:4000"
    env_file:
      - ./packages/backend/.env
    environment:
      - DB_URL=postgresql://admin:password@myjs-database:5432/myjs
    depends_on:
      - database
    entrypoint: /app/packages/backend/entrypoint.dev.sh

  database:
    container_name: myjs-database
    image: postgres:13-alpine
    ports:
      - "50000:5432"
    environment:
      - POSTGRES_INITDB_ARGS="--no-locale"
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myjs

volumes:
  volume-myjs-node_modules:
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
  volume-myjs-backend-node_modules:
    driver_opts:
      type: none
      device: ${PWD}/packages/backend/node_modules
      o: bind

networks:
  default:
    name: myjs
