version: "3.7"
services:
  backend:
    container_name: myjs-backend
    build: .
    volumes:
      - .:/app:cached
      - volume-myjs-node_modules:/app/node_modules:cached
    ports:
      - "4000:4000"
    env_file:
      - ./packages/backend/.env
    environment:
      - DB_URL=postgresql://admin:password@myjs-database:5432/myjs
    depends_on:
      - database

  database:
    container_name: myjs-database
    image: postgres:13-alpine
    ports:
      - "50000:5432"
    volumes:
      - appData:/app:cached
    working_dir: /app/packages/backend
    environment:
      - POSTGRES_INITDB_ARGS="--no-locale"
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myjs

volumes:
  appData:
  volume-myjs-node_modules:

networks:
  default:
    name: myjs
